### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by cbontoiu** [openPMD/openPMD-api#1367]
Hi,

I am trying to install the latest openPMD-api. I got it with

```git clone -b 0.14.4 https://github.com/openPMD/openPMD-api.git```

and then configured trying to use my ```openmpi``` installation (version 4.1):

```cmake -DopenPMD_USE_MPI=ON -DopenPMD_USE_ADIOS2=ON -DCMAKE_C_COMPILER=/usr/local/openmpi/bin/mpicc -DCMAKE_CXX_COMPILER=/usr/local/openmpi/bin/mpicxx -DCMAKE_INSTALL_PREFIX:PATH=~/lib/openPMD-api```

This went smooth with the following result:

```
- The C compiler identification is GNU 11.3.0
-- The CXX compiler identification is GNU 11.3.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/local/openmpi/bin/mpicc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/local/openmpi/bin/mpicxx - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found MPI_CXX: /usr/local/openmpi/bin/mpicxx (found version "3.1") 
-- Found MPI: TRUE (found version "3.1") found components: CXX 
-- Using the single-header code from /home/quasar/src/openPMD-api/share/openPMD/thirdParty/json/single_include/
-- nlohmann-json: Using INTERNAL version '3.9.1'
-- Could NOT find HDF5 (missing: HDF5_LIBRARIES HDF5_INCLUDE_DIRS C) (found version "")
-- Can NOT find 'adios_config' - set ADIOS_ROOT, ADIOS_DIR or INSTALL_PREFIX, or check your PATH
-- Could NOT find ADIOS (missing: ADIOS_LIBRARIES ADIOS_INCLUDE_DIRS) (Required is at least version "1.13.1")
-- Found MPI_C: /usr/local/openmpi/bin/mpicc (found version "3.1") 
-- Found MPI: TRUE (found version "3.1")  
-- Found ADIOS2: /usr/local/adios2/lib/cmake/adios2/adios2-config.cmake (found suitable version "2.8.3", minimum required is "2.7.0") found components: C CXX MPI 
-- Could NOT find Python (missing: Python_INCLUDE_DIRS Development.Module) (found suitable version "3.10.6", minimum required is "3.6.0")
-- <variant> supported (C++17 or newer): TRUE
-- Catch2: Using INTERNAL version '2.13.4'
-- Note: Skipping example and tool runs (missing openPMD-example-datasets)
-- Note: run
    /home/quasar/src/openPMD-api/share/openPMD/download_samples.sh
to add example files to samples/git-sample/ directory!
openPMD build configuration:
  library Version: 0.14.4
  openPMD Standard: 1.1.0
  C++ Compiler: GNU 11.3.0 
    /usr/local/openmpi/bin/mpicxx
  Installation prefix: /home/quasar/lib/openPMD-api
        bin: bin
        lib: lib
    include: include
      cmake: lib/cmake/openPMD
  Additionally, install following third party libraries:
    MPark.Variant: OFF
  Build Type: Release
  Library: shared
  CLI Tools: ON
  Examples: ON
  Testing: ON
  Invasive Tests: OFF
  Internal VERIFY: ON
  Build Options:
    MPI: ON
    HDF5: OFF
    ADIOS1: OFF
    ADIOS2: ON
    PYTHON: OFF
-- Configuring done
-- Generating done
-- Build files have been written to: /home/quasar/src/openPMD-api/build
```
But then installation failed:

```sudo make -j16 install```

```
/home/quasar/src/openPMD-api/share/openPMD/thirdParty/catch2/include/catch2/catch.hpp:10822:58: error: call to non-‘constexpr’ function ‘long int sysconf(int)’
10822 |     static constexpr std::size_t sigStackSize = 32768 >= MINSIGSTKSZ ? 32768 : MINSIGSTKSZ;
..
/home/quasar/src/openPMD-api/share/openPMD/thirdParty/catch2/include/catch2/catch.hpp:10881:45: error: size of array ‘altStackMem’ is not an integral constant-expression
10881 |     char FatalConditionHandler::altStackMem[sigStackSize] = {};
...
make: *** [Makefile:146: all] Error 2
```

Please help me to proceed with the installation.

Thank you.
Cristian

**Comment by franzpoeschel** [comment]
Hello Cristian,
this is a bug in an old version of Catch2, used by testing in our code. It is already updated on the dev branch.
If you just want to install and don't need tests, you can add `-DopenPMD_BUILD_TESTING=OFF` to your CMake call.

**Comment by cbontoiu** [comment]
@franzpoeschel Great. It worked. Thanks.

**Comment by cbontoiu** [comment]
@franzpoeschel 

There is also an error when installing with **pip**. Any suggestion, please?
**openPMD_USE_MPI=ON python3 -m pip install openpmd-api --no-binary openpmd-api**
```
DEPRECATION: --no-binary currently disables reading from the cache of locally built wheels. In the future --no-binary will not influence the wheel cache. pip 23.1 will enforce this behaviour change. A possible replacement is to use the --no-cache-dir option. You can use the flag --use-feature=no-binary-enable-wheel-cache to test the upcoming behaviour. Discussion can be found at https://github.com/pypa/pip/issues/11453
Collecting openpmd-api
  Using cached openPMD-api-0.14.5.post1.tar.gz (811 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: numpy<2.0.0,>=1.15.0 in ./anaconda3/lib/python3.9/site-packages (from openpmd-api) (1.21.5)
Requirement already satisfied: mpi4py>=2.1.0 in ./anaconda3/lib/python3.9/site-packages (from openpmd-api) (3.1.4)
Building wheels for collected packages: openpmd-api
  Building wheel for openpmd-api (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for openpmd-api (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [126 lines of output]
      running bdist_wheel
      running build
      running build_ext
      <string>:28: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
      -- The C compiler identification is GNU 11.3.0
      -- The CXX compiler identification is GNU 11.3.0
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: /usr/bin/cc - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: /usr/bin/c++ - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      -- Found MPI_CXX: /usr/local/openmpi/lib/libmpi.so (found version "3.1")
      -- Found MPI: TRUE (found version "3.1") found components: CXX
      -- Using the single-header code from /tmp/pip-install-i68tz6e9/openpmd-api_87bdb78c25d8473ea7cd7c45bcd376f9/share/openPMD/thirdParty/json/single_include/
      -- nlohmann-json: Using INTERNAL version '3.9.1'
      -- HDF5 C compiler wrapper is unable to compile a minimal HDF5 program.
      -- Could NOT find HDF5 (missing: HDF5_LIBRARIES HDF5_INCLUDE_DIRS C) (found version "")
      -- Can NOT find 'adios_config' - set ADIOS_ROOT, ADIOS_DIR or INSTALL_PREFIX, or check your PATH
      -- Could NOT find ADIOS (missing: ADIOS_LIBRARIES ADIOS_INCLUDE_DIRS) (Required is at least version "1.13.1")
      -- Found ADIOS2: /home/quasar/anaconda3/lib/cmake/adios2/adios2-config.cmake (found suitable version "2.7.1", minimum required is "2.7.0") found components: C CXX
      -- Found Python: /home/quasar/anaconda3/bin/python3 (found version "3.9.13") found components: Interpreter Development.Module
      -- pybind11 v2.6.2
      -- Performing Test HAS_FLTO
      -- Performing Test HAS_FLTO - Success
      -- pybind11: Using INTERNAL version 2.6.2
      -- <variant> supported (C++17 or newer): TRUE
      -- Python LTO/IPO: ON
      
      openPMD build configuration:
        library Version: 0.14.5
        openPMD Standard: 1.1.0
        C++ Compiler: GNU 11.3.0
          /usr/bin/c++
      
        Installation prefix: /usr/local
              bin: bin
              lib: lib
          include: include
            cmake: lib/cmake/openPMD
           python: lib/python3.9/site-packages
      
        Additionally, install following third party libraries:
          MPark.Variant: OFF
      
        Build Type: Release
        Library: static
        CLI Tools: OFF
        Examples: OFF
        Testing: OFF
        Invasive Tests: OFF
        Internal VERIFY: ON
        Build Options:
          MPI: ON
          HDF5: OFF
          ADIOS1: OFF
          ADIOS2: ON
          PYTHON: ON
      
      -- Configuring done
      CMake Error at CMakeLists.txt:626 (target_link_libraries):
        Target "openPMD" links to:
      
          adios2::cxx11_mpi
      
        but the target was not found.  Possible reasons include:
      
          * There is a typo in the target name.
          * A find_package call is missing for an IMPORTED target.
          * An ALIAS target is missing.
      
      
      
      -- Generating done
      CMake Generate step failed.  Build files cannot be regenerated correctly.
      Traceback (most recent call last):
        File "/home/quasar/anaconda3/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/quasar/anaconda3/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/quasar/anaconda3/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
        File "/tmp/pip-build-env-a1a9zksd/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 413, in build_wheel
          return self._build_with_temp_dir(['bdist_wheel'], '.whl',
        File "/tmp/pip-build-env-a1a9zksd/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 398, in _build_with_temp_dir
          self.run_setup()
        File "/tmp/pip-build-env-a1a9zksd/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 335, in run_setup
          exec(code, locals())
        File "<string>", line 168, in <module>
        File "/tmp/pip-build-env-a1a9zksd/overlay/lib/python3.9/site-packages/setuptools/__init__.py", line 108, in setup
          return distutils.core.setup(**attrs)
        File "/tmp/pip-build-env-a1a9zksd/overlay/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/tmp/pip-build-env-a1a9zksd/overlay/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/tmp/pip-build-env-a1a9zksd/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/tmp/pip-build-env-a1a9zksd/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 1213, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-a1a9zksd/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-a1a9zksd/overlay/lib/python3.9/site-packages/wheel/bdist_wheel.py", line 325, in run
          self.run_command("build")
        File "/tmp/pip-build-env-a1a9zksd/overlay/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/tmp/pip-build-env-a1a9zksd/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 1213, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-a1a9zksd/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-a1a9zksd/overlay/lib/python3.9/site-packages/setuptools/_distutils/command/build.py", line 132, in run
          self.run_command(cmd_name)
        File "/tmp/pip-build-env-a1a9zksd/overlay/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/tmp/pip-build-env-a1a9zksd/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 1213, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-a1a9zksd/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "<string>", line 36, in run
        File "<string>", line 108, in build_extension
        File "/home/quasar/anaconda3/lib/python3.9/subprocess.py", line 373, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['cmake', '/tmp/pip-install-i68tz6e9/openpmd-api_87bdb78c25d8473ea7cd7c45bcd376f9', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/tmp/pip-install-i68tz6e9/openpmd-api_87bdb78c25d8473ea7cd7c45bcd376f9/build/lib.linux-x86_64-cpython-39/openpmd_api', '-DCMAKE_PYTHON_OUTPUT_DIRECTORY=/tmp/pip-install-i68tz6e9/openpmd-api_87bdb78c25d8473ea7cd7c45bcd376f9/build/lib.linux-x86_64-cpython-39/', '-DPython_EXECUTABLE=/home/quasar/anaconda3/bin/python3', '-DopenPMD_USE_PYTHON:BOOL=ON', '-DopenPMD_USE_MPI:BOOL=ON', '-DopenPMD_BUILD_CLI_TOOLS:BOOL=OFF', '-DopenPMD_BUILD_EXAMPLES:BOOL=OFF', '-DopenPMD_BUILD_TESTING:BOOL=OFF', '-DopenPMD_BUILD_SHARED_LIBS:BOOL=OFF', '-DHDF5_USE_STATIC_LIBRARIES:BOOL=OFF', '-DADIOS_USE_STATIC_LIBS:BOOL=OFF', '-DCMAKE_BUILD_WITH_INSTALL_RPATH:BOOL=ON', '-DCMAKE_INSTALL_RPATH_USE_LINK_PATH:BOOL=OFF', '-DCMAKE_INSTALL_RPATH=$ORIGIN', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for openpmd-api
Failed to build openpmd-api
ERROR: Could not build wheels for openpmd-api, which is required to install pyproject.toml-based projects
```

**Comment by ax3l** [comment]
Did you provide ADIOS2 as pre-installed dependency and does ADIOS2 have MPI support enabled?

Without ADIOS2 it's:
```console
openPMD_USE_ADIOS1=OFF openPMD_USE_MPI=ON python3 -m pip install openpmd-api --no-binary openpmd-api
```

but I think the underlying issue is that you forgot to turn on MPI when building ADIOS2.

**Comment by cbontoiu** [comment]
Hi @ax3l and thanks for your swift reply. I guess you mean that i should install this package
https://anaconda.org/williamfgc/adios2-openmpi
The problem is that this does not support Python 3.9, which comes with the latest Anaconda version.
On a clean installation of Anaconda:
```conda install -c conda-forge mpi4py``` works
```conda install -c "williamfgc/label/full" adios2-openmpi``` fails as shown below

```
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: / 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                           

UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - adios2-openmpi -> python[version='>=3.7,<3.8.0a0']

Your python: python=3.9

If python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you are constrained to. Note that conda will not
change your python version to a different minor version unless you explicitly specify
that.

The following specifications were found to be incompatible with your system:

  - feature:/linux-64::__glibc==2.35=0
  - feature:|@/linux-64::__glibc==2.35=0

Your installed version is: 2.35
```
