### ISSUE TITLE
python interface set_software(arg1, arg2) breaks readability

### ISSUE THREAD

**Issue by PrometheusPi** [openPMD/openPMD-api#798]
**Brief description**
Following the `firstwrite.py`and `firstread.py`introduction, one could also use the `set_software` method to specify the software used and since recently define the software version as second argument. Specifying the second argument however breaks the readability of the openPMD files (at least with ADIOS2).  

**To Reproduce**

```python
import openpmd_api as io
import numpy as np

# write file
series = io.Series("test_simData_%06T.bp", io.Access_Type.create)
i = series.iterations[1000]

series.set_author("Jim Knopf")
series.set_attribute("dinner", "Pizza and Coke")

series.set_software("jupyter", "abc_1.2.3")

series.flush()
del series

# read file
series = io.Series("test_simData_%06T.bp", io.Access_Type.read_only)
```

leads to the following error:
```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-124-4ca1f3f8499d> in <module>
----> 1 series = io.Series("test_simData_%06T.bp", io.Access_Type.read_only)

RuntimeError: [ADIOS2] Requested attribute (/openPMD) not found in backend.
```

The same happens if the default version is used:
```python
series.set_software("jupyter")
```

**Expected behavior**
However not using `set_software`:
```python
import openpmd_api as io
import numpy as np

# write file
series = io.Series("test_simData_%06T.bp", io.Access_Type.create)
i = series.iterations[1000]

series.set_author("Jim Knopf")
series.set_attribute("dinner", "Pizza and Coke")


series.flush()
del series

# read file
series = io.Series("test_simData_%06T.bp", io.Access_Type.read_only)
i = series.iterations[1000]

print(series.openPMD)
print(series.author)
print(series.software)
print(series.software_version)
print(series.get_attribute("dinner"))
```

returns
```
1.1.0
Jim Knopf
openPMD-api
0.12.0-alpha
Pizza and Coke
```

using the deprecated approach also works:
```python
import openpmd_api as io
import numpy as np

# write file
series = io.Series("test_simData_%06T.bp", io.Access_Type.create)
i = series.iterations[1000]

series.set_author("Jim Knopf")
series.set_attribute("dinner", "Pizza and Coke")

series.set_software("jupyter")
series.set_software_version("3.1415")

series.flush()
del series

# read file
series = io.Series("test_simData_%06T.bp", io.Access_Type.read_only)
i = series.iterations[1000]

print(series.openPMD)
print(series.author)
print(series.software)
print(series.software_version)
print(series.get_attribute("dinner"))
```

returns
```
1.1.0
Jim Knopf
jupyter
3.1415
Pizza and Coke
```

**Software Environment**
 - version of openPMD-api: 0.12.0-alpha
 - installed openPMD-api via: conda-forge
 - operating system: CentOS Linux 7
 - machine: hemera/HZDR
 - name and version of Python implementation: 3.8.6 (packaged by conda-forge)
 - version of HDF5: 1.10.6
 - version of ADIOS1: 1.13.1
 - version of ADIOS2: 2.6.0

**Additional context**
While implementing the test for the missing `machine` attribute in #796, I discovered that the `software`and `software_version` attributes were set bet never checked. Implementing the check resulted in errors.

**Comment by ax3l** [comment]
Hi @PrometheusPi,

thank you for the report! Ouch, this is covered on the write end in `test/python/unittest/API/APITest.py`, but we do calls to both deprecated and new APIs and this masks the bug.

**Comment by ax3l** [comment]
@franzpoeschel I think this might be related to the delayed attributes challenge we have with ADIOS2. We set the "software"-attribute default in `Series::initDefaults()`.

Potentially logic like this would be best written on `Iteration::close()` (for file-based) or `Series::close()` (for group- and variable-based) iteration encoding, I think.

**Comment by ax3l** [comment]
I am able to fail the unit test even with JSON, so this is more of a internal logic issue per se (or we delay all backends' attribute writes as a work-around):
```diff
diff --git a/test/python/unittest/API/APITest.py b/test/python/unittest/API/APITest.py
index d2428436..17ec8643 100644
--- a/test/python/unittest/API/APITest.py
+++ b/test/python/unittest/API/APITest.py
@@ -117,6 +117,7 @@ class APITest(unittest.TestCase):
         self.assertEqual(len(i.particles), 0)
 
     def attributeRoundTrip(self, file_ending):
+        print("attributeRoundTrip with {0}".format(file_ending))
         # write
         series = io.Series(
             "unittest_py_API." + file_ending,
@@ -124,8 +125,8 @@ class APITest(unittest.TestCase):
         )
 
         # meta data
-        series.set_software("nonsense")  # with unspecified version
-        series.set_software_version("1.2.3")  # deprecated
+        #series.set_software("nonsense")  # with unspecified version
+        #series.set_software_version("1.2.3")  # deprecated
         series.set_software("openPMD-api-python-tests", "0.42.0")
         series.machine = "testMachine"
 
@@ -254,6 +255,8 @@ class APITest(unittest.TestCase):
             io.Access.read_only
         )
 
+        self.assertEqual(series.software, "openPMD-api-python-tests")
+        self.assertEqual(series.software_version, "0.42.0")
         self.assertEqual(series.machine, "testMachine")
 
         self.assertEqual(series.get_attribute("char"), "c")
```
```
======================================================================
FAIL: testAttributes (API.APITest.APITest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "openPMD-api/test/python/unittest/API/APITest.py", line 376, in testAttributes
    self.attributeRoundTrip(ext)
  File "openPMD-api/test/python/unittest/API/APITest.py", line 258, in attributeRoundTrip
    self.assertEqual(series.software, "openPMD-api-python-tests")
AssertionError: 'openPMD-api' != 'openPMD-api-python-tests'
- openPMD-api
+ openPMD-api-python-tests
```

Update: I checked the created file `unittest_py_API.json` and the attribute is properly written. Must be a read issue then.

**Comment by ax3l** [comment]
I could not 100% reproduce your example @PrometheusPi, but fixed a related bug with #812 that popped up when extending the read API unit test (see above).

Does this solve your problem as well?

**Comment by ax3l** [comment]
I think in your example might be another issue, namely that there is an iteration created without ever writing data to it (should also be addressed).

This should with #812 be readable, though:
```py
series = io.Series("test_simData_%06T.bp", io.Access_Type.create)
# i = series.iterations[1000]  # comment me

series.set_author("Jim Knopf")
series.set_attribute("dinner", "Pizza and Coke")
series.set_software("jupyter", "abc_1.2.3")

del series  # implies series.flush()
```

**Comment by ax3l** [comment]
Hm, cannot see an issue with the empty iteration. Maybe #812 is all you need?

```diff
diff --git a/test/python/unittest/API/APITest.py b/test/python/unittest/API/APITest.py
index 01f17b47..4a268dd4 100644
--- a/test/python/unittest/API/APITest.py
+++ b/test/python/unittest/API/APITest.py
@@ -116,6 +116,27 @@ class APITest(unittest.TestCase):
         self.assertEqual(len(i.meshes), 2)
         self.assertEqual(len(i.particles), 0)
 
+    def attributeRoundTripEmptyIt(self, file_ending):
+        # write
+        series = io.Series(
+            "unittest_py_API_empty_iteration." + file_ending,
+            io.Access.create
+        )
+
+        it = series.iterations[1000]  # noqa
+
+        # meta data
+        series.machine = "testMachine"
+
+        del series
+
+        # read back
+        series = io.Series(
+            "unittest_py_API_empty_iteration." + file_ending,
+            io.Access.read_only
+        )
+        self.assertEqual(series.machine, "testMachine")
+
     def attributeRoundTrip(self, file_ending):
         # write
         series = io.Series(
@@ -373,6 +394,7 @@ class APITest(unittest.TestCase):
     def testAttributes(self):
         for ext in io.file_extensions:
             self.attributeRoundTrip(ext)
+            self.attributeRoundTripEmptyIt(ext)
 
     def makeConstantRoundTrip(self, file_ending):
         # write
```
passes.

**Comment by PrometheusPi** [comment]
@ax3l I will have a look at the fixes.
